### ISSUE TITLE
0.30 tournament tracking

### ISSUE THREAD

**Issue by rawlins** [crawl/dcss_tourney#13]
- [ ] review and merge #12
- [ ] come up with vault rune challenge banner
- [ ] merge username blocklist code from scoring/webtiles
- [ ] probably other things...

**Comment by rawlins** [comment]
I've done some analysis of what banners players did and didn't do in t0.29. Quick summary:

* least popular: trog (brute force, 36+6+9=51), vehumet (ruthless efficiency, 35+32+1=68), lugonu (spiteful, 89+3+7=99), qazlal (prophet, 104+63+22=189)
* most popular: ely (pious, 883+152+16=1051), chei (slow and steady, 996+65+23=1084), gozag (avarice, 894+475+4=1373), tso (vow of courage, 1371+94+19=1484)
* most popular t3 are hepl, zin, makhleb
* player banner counts by tier: 10236, 2626, 817
* for all that heretic has been getting some hate, it's solidly middle of the pack in terms of popularity: 263 + 157 + 14 = 434
* for various banners, but especially wjc (sifu), kiku (lord of darkness), ru (ascetic), sif (lorekeeper), there is a strong skew towards the tier 1, which could indicate some need for rebalancing.
* For the other tiers nothing pops out like that except that it appears that for makhleb (speed demon) essentially no one who does it stops at t1


For reference, the query I was using is as follows. (Anyone with db access should be able to use this, but I was having some trouble getting into the cdo db -- I ran this on a local duplicate.)

```
select banner,
    t1, t1 / total as t1per,
    t2, t2 / total as t2per,
    t3, t3 / total as t3per, total
    from (select
        banner,
        sum(case when prestige = 1 then 1 else 0 end) as t1,
        sum(case when prestige = 2 then 1 else 0 end) as t2,
        sum(case when prestige = 3 then 1 else 0 end) as t3,
        sum(case when prestige <= 3 then 1 else 0 end) as total
    from player_banners group by banner) as sub;
```

**Comment by rawlins** [comment]
And, here's a set of possible changes based on this banner data and other feedback.

**banner additions/removals/swaps**
* remove spiteful, replace with a loguno-specific challenge (ge0ff proposal or variant?)
	- "Find Lugonu's altar in the Abyss, champion the god, and win the game". 3rd tier could require joining Lugonu on A:7.
* remove brute force (trog). Perhaps: trog takes over the current graceful (usk)?
* new banner for rune get challenges, perhaps usk? preliminary ideas only -- t1: get abyss rune as first rune, t2: get silver rune as first rune, t3 get golden rune as first rune
* pious -> ignis (sentei proposal)
	- or, keep pious with ely (only category changes, not banner), and ignis gets something new. Lightli: “get rune with Ignis” -> “win with Ignis” -> “win with Ignis and 15 runes”.

**banner tweaks**
* increase time for speed demon (makhleb) t1? 27min is thematic but it seems like non-speedrunners just can't/won't do it. Though I will say from the stats, it isn't entirely obvious what to pick. 54 is probably too high? It might be ok: median is around 75min.
	- !lm * t0.29 !bot !fo br.end=d x=median(dur / 60)
	- !lm * t0.29 br.end=d s=${trunc(int(dur),60) / 60} -graph
* ruthless efficiency, t1 -> before xl 13, t2 -> before xl 17, t3 -> before xl 22
	- these may seem like big changes, but in t0.29 only 1 person got t3, and 68 people got any tier
	- !lm * t0.29 !bot br.end=lair s=xl -graph
	- !lm * t0.29 !bot urune=1 s=xl -graph
	- !lg * t0.29 !bot won s=xl -graph
	- in t0.29, 22 games would be eligible for this new t3 (even going up to <xl24 wouldn't be crazy)
* wjc (sifu): adjust t2 to 12k turns, t3 to a different location (what?)
* ascetic (ru): t2 (and maybe t3) should be relaxed somehow. Enter lair? Choose between potions and scrolls?
* lorekeeper (sif): tweak numbers so that t2 and t3 are more possible. t2: past 20, t3: 15?

**possible change points with no current proposal:**
* qazlal (prophet) is reasonably unpopular, but doesn't seem awful to me
* players report hating heretic, but lots of people do it. Can it be made better?
* lord of darkness mostly doesn't have people doing t2 and t3, and also would have overlap with the new rune get banner. But t1 is good. How to fix?
